global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'fastapi-metrics'
    scrape_interval: '15s'
    scrape_timeout: '10s'
    static_configs:
      - targets: ['fastapi-metrics:8000']
    honor_labels: true
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
